# Generated by Django 5.1.6 on 2025-02-20 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "cedula",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_cedula",
                                message="Ingrese una cédula venezolana válida (Ej: V-12345678)",
                                regex="^[V|E|P]-\\d{7,8}$",
                            )
                        ],
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254,
                        validators=[
                            django.core.validators.EmailValidator(
                                code="invalid_email",
                                message="Ingrese un correo electrónico válido",
                            )
                        ],
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("apellido", models.CharField(max_length=64)),
            ],
        ),
    ]
