# Generated by Django 5.1.6 on 2025-04-22 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "cedula",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1000000,
                                "Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
                            ),
                            django.core.validators.MaxValueValidator(
                                35000000,
                                "Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
                            ),
                        ],
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254,
                        validators=[
                            django.core.validators.EmailValidator(
                                code="correo_invalido",
                                message="Ingrese un correo electrónico válido",
                            )
                        ],
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("apellido", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "docentes",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cedula__gte", 1000000)),
                        name="cedula_mayor_que",
                        violation_error_message="Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cedula__lte", 35000000)),
                        name="cedula_menor_que",
                        violation_error_message="Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
                    ),
                ],
            },
        ),
    ]
