# Generated by Django 5.1.6 on 2025-02-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion_docente", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="docente",
            table="docentes",
        ),
    ]
