# Generated by Django 5.1.6 on 2025-04-22 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion_docente", "0004_alter_docente_cedula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="cedula",
            field=models.IntegerField(
                max_length=20,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.MinValueValidator(
                        1000000,
                        "Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
                    ),
                    django.core.validators.MaxValueValidator(
                        35000000,
                        "Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="docente",
            constraint=models.CheckConstraint(
                condition=models.Q(("cedula__gte", 1000000)),
                name="cedula_mayor_que",
                violation_error_message="Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
            ),
        ),
        migrations.AddConstraint(
            model_name="docente",
            constraint=models.CheckConstraint(
                condition=models.Q(("cedula__lte", 35000000)),
                name="cedula_menor_que",
                violation_error_message="Ingrese un número de cédula válido (Entre 1.000.000 y 35.000.000)",
            ),
        ),
    ]
