# Generated by Django 5.1.6 on 2025-02-20 05:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autenticacion_docente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadCurricular",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "trayecto",
                    models.SmallIntegerField(
                        choices=[(0, "Inicial"), (1, "1"), (2, "2"), (3, "3"), (4, "4")]
                    ),
                ),
                (
                    "semestre",
                    models.SmallIntegerField(
                        choices=[("NA", "No Aplica"), (1, "1"), (2, "2")]
                    ),
                ),
                (
                    "unidades_credito",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Las unidades de crédito no pueden ser menores a 1."
                            ),
                            django.core.validators.MaxValueValidator(
                                10,
                                "Las unidades de crédito no pueden ser mayores a 10.",
                            ),
                        ]
                    ),
                ),
                ("nombre", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="PlanAprendizaje",
            fields=[
                (
                    "codigo_grupo",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                (
                    "nucleo",
                    models.CharField(
                        choices=[
                            ("FLO", "La Floresta"),
                            ("URB", "La Urbina"),
                            ("ALT", "Altagracia"),
                            ("CRY", "Carayaca"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("N", "Nocturno"),
                            ("V", "Vespertino"),
                            ("M", "Mañana"),
                        ],
                        max_length=3,
                    ),
                ),
                ("pnf", models.CharField(max_length=32)),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 2, 20, 5, 30, 12, 594734)
                    ),
                ),
                ("fecha_modificacion", models.DateTimeField(null=True)),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autenticacion_docente.docente",
                    ),
                ),
                (
                    "unidad_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_planes.unidadcurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjetivoPlanAprendizaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=32)),
                ("contenido", models.TextField()),
                ("criterio_logro", models.TextField()),
                (
                    "estrategia_didactica",
                    models.CharField(
                        choices=[
                            ("CL", "Clase magistral"),
                            ("TR", "Trabajo en grupo"),
                            ("DE", "Debate"),
                            ("EP", "Estudio de caso"),
                            ("AP", "Aprendizaje basado en problemas"),
                            ("PY", "Proyecto"),
                            ("TA", "Taller"),
                            ("LB", "Laboratorio"),
                            ("EX", "Exposición"),
                            ("SE", "Seminario"),
                            ("TI", "Tutoría individual"),
                            ("TC", "Tutoría colectiva"),
                            ("VA", "Visita guiada"),
                            ("PC", "Práctica de campo"),
                            ("EV", "Evaluación"),
                            ("OT", "Otras"),
                        ],
                        default="CL",
                        max_length=4,
                    ),
                ),
                (
                    "duracion_horas",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                10, "Las horas de duración no pueden ser menores a 10."
                            ),
                            django.core.validators.MaxValueValidator(
                                200,
                                "Las horas de duración no pueden ser mayores a 200.",
                            ),
                        ]
                    ),
                ),
                (
                    "plan_aprendizaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_planes.planaprendizaje",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=32)),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 2, 20, 5, 30, 12, 596701)
                    ),
                ),
                ("fecha_modificacion", models.DateTimeField(null=True)),
                (
                    "plan_aprendizaje",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_planes.planaprendizaje",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPlanEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrumento_evaluacion",
                    models.CharField(
                        choices=[
                            ("PR", "Prueba escrita (objetiva)"),
                            ("PE", "Prueba escrita (ensayo)"),
                            ("PO", "Prueba oral"),
                            ("TR", "Trabajo escrito"),
                            ("TA", "Tarea"),
                            ("EX", "Examen práctico"),
                            ("PY", "Proyecto"),
                            ("IN", "Informe"),
                            ("PC", "Participación en clase"),
                            ("AC", "Actividades colaborativas"),
                            ("DE", "Debate"),
                            ("EX", "Exposición oral"),
                            ("SE", "Seminario"),
                            ("CT", "Control de lectura"),
                            ("CV", "Cuestionario"),
                            ("DI", "Diario reflexivo"),
                            ("CA", "Carpeta de trabajos"),
                            ("AU", "Autoevaluación"),
                            ("CO", "Coevaluación"),
                            ("OT", "Otras"),
                        ],
                        default="PR",
                        max_length=4,
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.CharField(
                        choices=[
                            ("DI", "Diagnóstica"),
                            ("FO", "Formativa"),
                            ("SU", "Sumativa"),
                            ("AU", "Autoevaluación"),
                            ("CO", "Coevaluación"),
                        ],
                        default="FO",
                        max_length=4,
                    ),
                ),
                ("habilidades_a_evaluar", models.TextField()),
                (
                    "peso",
                    models.SmallIntegerField(
                        choices=[
                            (5, "5%"),
                            (10, "10%"),
                            (15, "15%"),
                            (20, "20%"),
                            (25, "25%"),
                        ],
                        default=15,
                    ),
                ),
                ("fecha_planificada", models.DateField()),
                (
                    "plan_evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_planes.planevaluacion",
                    ),
                ),
            ],
        ),
    ]
