# Generated by Django 5.1.6 on 2025-02-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_planes", "0004_alter_planaprendizaje_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="itemplanevaluacion",
            table="items_plan_de_evaluacion",
        ),
        migrations.AlterModelTable(
            name="objetivoplanaprendizaje",
            table="objetivos_plan_de_aprendizaje",
        ),
        migrations.AlterModelTable(
            name="planaprendizaje",
            table="plan_de_aprendizaje",
        ),
        migrations.AlterModelTable(
            name="planevaluacion",
            table="planes_de_evaluacion",
        ),
        migrations.AlterModelTable(
            name="unidadcurricular",
            table="unidades_curriculares",
        ),
    ]
