# Generated by Django 5.1.6 on 2025-02-27 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_planes", "0007_alter_planaprendizaje_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemplanevaluacion",
            name="objetivo_asociado",
        ),
        migrations.AddField(
            model_name="objetivoplanaprendizaje",
            name="evaluacion_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion_planes.itemplanevaluacion",
            ),
        ),
    ]
