# Generated by Django 5.1.6 on 2025-03-04 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_planes", "0008_remove_itemplanevaluacion_objetivo_asociado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetivoplanaprendizaje",
            name="duracion_horas",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        2, "Las horas de duración no pueden ser menores a 2."
                    ),
                    django.core.validators.MaxValueValidator(
                        9, "Las horas de duración no pueden ser mayores a 9."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="objetivoplanaprendizaje",
            name="evaluacion_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="objetivos_asociados",
                to="gestion_planes.itemplanevaluacion",
            ),
        ),
        migrations.AlterField(
            model_name="planaprendizaje",
            name="codigo_grupo",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="planaprendizaje",
            name="nucleo",
            field=models.CharField(
                choices=[
                    ("FLO", "La Floresta"),
                    ("URB", "La Urbina"),
                    ("ALT", "Altagracia"),
                    ("LGA", "La Guaira"),
                ],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="planaprendizaje",
            name="turno",
            field=models.CharField(
                choices=[
                    ("N", "Nocturno"),
                    ("V", "Vespertino"),
                    ("M", "Matutino"),
                    ("S", "Sabatino"),
                ],
                max_length=3,
            ),
        ),
    ]
