# Generated by Django 5.1.6 on 2025-03-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_planes",
            "0009_alter_objetivoplanaprendizaje_duracion_horas_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetivoplanaprendizaje",
            name="titulo",
            field=models.CharField(max_length=64),
        ),
    ]
