# Generated by Django 5.1.6 on 2025-04-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_planes", "0012_alter_planevaluacion_nombre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemplanevaluacion",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="objetivoplanaprendizaje",
            options={"ordering": ["id"]},
        ),
    ]
