# Generated by Django 5.1.6 on 2025-04-22 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_planes", "0013_alter_itemplanevaluacion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetivoplanaprendizaje",
            name="duracion_horas",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        2,
                        "La duración en horas de un objetivo debe ser de mínimo 2 y máximo 9.",
                    ),
                    django.core.validators.MaxValueValidator(
                        9,
                        "La duración en horas de un objetivo debe ser de mínimo 2 y máximo 9.",
                    ),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="itemplanevaluacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("peso__in", [5, 10, 15, 20, 25])),
                name="validar_peso",
                violation_error_message="Los pesos de evaluación válidos son [(5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%')]",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemplanevaluacion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "instrumento_evaluacion__in",
                        [
                            "PR",
                            "PE",
                            "PO",
                            "TR",
                            "TA",
                            "EX",
                            "PY",
                            "IN",
                            "PC",
                            "AC",
                            "DE",
                            "EX",
                            "SE",
                            "CT",
                            "CV",
                            "DI",
                            "CA",
                            "AU",
                            "CO",
                            "OT",
                        ],
                    )
                ),
                name="validar_instrumento_evaluacion",
                violation_error_message="Los instrumentos de evaluación válidos son [('PR', 'Prueba escrita (objetiva)'), ('PE', 'Prueba escrita (ensayo)'), ('PO', 'Prueba oral'), ('TR', 'Trabajo escrito'), ('TA', 'Tarea'), ('EX', 'Examen práctico'), ('PY', 'Proyecto'), ('IN', 'Informe'), ('PC', 'Participación en clase'), ('AC', 'Actividades colaborativas'), ('DE', 'Debate'), ('EX', 'Exposición oral'), ('SE', 'Seminario'), ('CT', 'Control de lectura'), ('CV', 'Cuestionario'), ('DI', 'Diario reflexivo'), ('CA', 'Carpeta de trabajos'), ('AU', 'Autoevaluación'), ('CO', 'Coevaluación'), ('OT', 'Otras')]",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemplanevaluacion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tipo_evaluacion__in", ["DI", "FO", "SU", "AU", "CO"])
                ),
                name="validar_tipo_evaluacion",
                violation_error_message="Los tipos de evaluación válidos son [('DI', 'Diagnóstica'), ('FO', 'Formativa'), ('SU', 'Sumativa'), ('AU', 'Autoevaluación'), ('CO', 'Coevaluación')]",
            ),
        ),
        migrations.AddConstraint(
            model_name="objetivoplanaprendizaje",
            constraint=models.CheckConstraint(
                condition=models.Q(("duracion_horas__gte", 2)),
                name="duracion_horas_mayor_que",
                violation_error_message="La duración en horas de un objetivo debe ser de mínimo 2 y máximo 9.",
            ),
        ),
        migrations.AddConstraint(
            model_name="objetivoplanaprendizaje",
            constraint=models.CheckConstraint(
                condition=models.Q(("duracion_horas__lte", 9)),
                name="duracion_horas_menor_que",
                violation_error_message="La duración en horas de un objetivo debe ser de mínimo 2 y máximo 9.",
            ),
        ),
        migrations.AddConstraint(
            model_name="objetivoplanaprendizaje",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "estrategia_didactica__in",
                        [
                            "CL",
                            "TR",
                            "DE",
                            "EP",
                            "AP",
                            "PY",
                            "TA",
                            "LB",
                            "EX",
                            "SE",
                            "TI",
                            "TC",
                            "VA",
                            "PC",
                            "EV",
                            "OT",
                        ],
                    )
                ),
                name="validar_estrategia_didactica",
                violation_error_message="Los valores válidos para la estrategia didáctica son [('CL', 'Clase magistral'), ('TR', 'Trabajo en grupo'), ('DE', 'Debate'), ('EP', 'Estudio de caso'), ('AP', 'Aprendizaje basado en problemas'), ('PY', 'Proyecto'), ('TA', 'Taller'), ('LB', 'Laboratorio'), ('EX', 'Exposición'), ('SE', 'Seminario'), ('TI', 'Tutoría individual'), ('TC', 'Tutoría colectiva'), ('VA', 'Visita guiada'), ('PC', 'Práctica de campo'), ('EV', 'Evaluación'), ('OT', 'Otras')]",
            ),
        ),
    ]
